spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.86ff01a3a37ed308
            client-secret: 3cf1050c928f3030023110c9e03d1bc99d0f09f0
  data:
    cassandra:
      keyspace-name: main
      username: LlwWchZjbrIFgmGqOwqpiHHs
      password: MMDOD_Xrm_ptWMRcJehEAXp7j38,IpJigZWcyzl7J5KuO10txfA2665JrEOCFs7ctQ.4H-UZdudyKqu0IZ+k5awOsQeRgMInRB3hZHKRgaWL4EC262vpCcqIIkQ_g+B-
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
astra:
  db:
    id: f55ad937-04b8-4074-8f70-35b12269b306-1
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:LlwWchZjbrIFgmGqOwqpiHHs:f5ac67f7fa2c3e01f91ecc1b49d643aadfc0f629316cc05598baeb1d0734f669
datastax.astra:
  secure-connect-bundle: secure-connect-inbox-app.zip